<?php
# This file was automatically generated by the MediaWiki 1.18.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename      = "CurriculumWiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/wiki";
$wgScriptExtension  = ".php";
## The protocol and server name to use in fully-qualified URLs
$wgServer           = "http://localhost";

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "$wgStylePath/common/images/wiki-logo-1.png";
//$wgLogo             = "$wgStylePath/common/images/wiki-logo-2.png";
$wgAllowUserJs=true;
## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "f.qutaifan@gmail.com";
$wgPasswordSender   = "f.qutaifan@gmail.com";

$wgEnotifUserTalk      = false; # UPO
$wgEnotifWatchlist     = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "wikidb";
$wgDBuser           = "root";
$wgDBpassword       = "";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=utf8";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType    = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons  = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "4c7bf1e328c6b17cd6caa0494f6cf733bf635efb8405e27c81aed29eef5e4000";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "ae3c8eeb41578893";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook', 'vector':
//$wgDefaultSkin = "vector";
$wgDefaultSkin = "monobook";


## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl  = "http://creativecommons.org/licenses/by-nc-sa/4.0/";
$wgRightsText = " a Creative Commons Attribution Non-Commercial Share Alike";
$wgRightsIcon = "{$wgStylePath}/common/images/cc-by-nc-sa.png";
# $wgRightsCode = ""; # Not yet used

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

# Query string length limit for ResourceLoader. You should only set this if
# your web server has a query string length limit (then set it to that limit),
# or if you have suhosin.get.max_value_length set in php.ini (then set it to
# that value)
$wgResourceLoaderMaxQueryLength = -1;

# The following permissions were set based on your choice in the installer
//$wgGroupPermissions['*']['createaccount'] = true;
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['sysop']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['user']['upload']= false;
$wgGroupPermissions['*']['bulkcreate']= false;
$wgGroupPermissions['sysop']['bulkcreate']= true;
$wgGroupPermissions['user']['GenerateAssessment']= true;
$wgUseAjax = true;
# Enabled Extensions. Most extensions are enabled by including the base extension file here
# but check specific extension documentation for more details
# The following extensions were automatically enabled:
//require_once( "$IP/extensions/ConfirmEdit/ConfirmEdit.php");
require_once( "$IP/extensions/Gadgets/Gadgets.php");
require_once( "$IP/extensions/Nuke/Nuke.php");
require_once( "$IP/extensions/ParserFunctions/ParserFunctions.php");
require_once( "$IP/extensions/Renameuser/Renameuser.php");
require_once( "$IP/extensions/Vector/Vector.php");
require_once( "$IP/extensions/ApprovedRevs/ApprovedRevs.php" );
require_once( "$IP/extensions/MultiUpload/MultiUpload.php" );
require_once( "$IP/extensions/ImportUsers/ImportUsers.php");
//require_once( "$IP/extensions/UsageStatistics/UsageStatistics.php" );
$wgUploadNavigationUrl = "{$wgScriptPath}/index.php?title=Special:MultipleUpload";
//$wgMaxUploadFiles = 1;
require_once( "$IP/extensions/CategoryTree/CategoryTree.php");
$egApprovedRevsShowApproveLatest = true;
$wgGroupPermissions['Editors'] = $wgGroupPermissions['user'];
$wgGroupPermissions['Editors']['approverevisions'] = true;

/*# Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMessageCacheType = CACHE_ACCEL;
$wgCacheDirectory = 'E:/wamp/www/Wiki/Cash';
$wgParserCacheType = CACHE_ACCEL;
$wgMemCachedServers = array();
$wgUseGzip = true;
$wgEnableSidebarCache = true;

# NO DB HITS!
$wgDisableCounters = true;
$wgMiserMode = true;

# Text cache
$wgCompressRevisions = true; // use with care (see talk page)
$wgRevisionCacheExpiry = 3*24*3600;
$wgParserCacheExpireTime = 14*24*3600;

# Diffs
#$wgDiff = 'C:/Server/xampp/htdocs/MW/bin/GnuWin32/bin/diff.exe';
#$wgDiff3 = 'C:/Server/xampp/htdocs/MW/bin/GnuWin32/bin/diff3.exe';*/








$wgEnableMWSuggest = true;
$wgCategoryTreeSidebarRoot = 'Category:Common core curriculum standards';
$wgCategoryTreeForceHeaders = true;
$wgCategoryTreeCategoryPageOptions['mode'] = 'all';
$wgCategoryTreeDefaultOptions['hideroot'] = 'off';
$wgCategoryTreeSidebarOptions['hideroot'] = false;
$wgCategoryTreeSidebarOptions['mode'] = CT_MODE_ALL;
# End of automatically generated settings.
# Add more configuration options below.
$wgShowExceptionDetails = true;
#Set Default Timezone
$wgLocaltimezone = "Asia/Karachi";
$oldtz = getenv("TZ");
putenv("TZ=$wgLocaltimezone");
# Versions before 1.7.0 used $wgLocalTZoffset as hours.
# After 1.7.0 offset as minutes
$wgLocalTZoffset = date("Z") / 60;
putenv("TZ=$oldtz");


